# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Manuel Baesler and contributors

[package]
name = "madt"
description = "Fuzz target: madt"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "madt"
path = "src/main.rs"
test = false
bench = false
doc = false

[dependencies]
fuzz-support.workspace = true
kernel-acpi.workspace = true

[lints]
workspace = true
