# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Manuel Baesler and contributors

[package]
name = "crypto-rng"
description = "A ChaCha20 deterministic random bit generator over an entropy source"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[features]
test-doubles = []

[dependencies]
crypto-aead.workspace = true
crypto-ct.workspace = true

[dev-dependencies]
test-support.workspace = true

[lints]
workspace = true
