# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Manuel Baesler and contributors

[package]
name = "text-raster"
description = "Deterministic outline and paint stream rasterization"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
text-core = { workspace = true, default-features = false }

[lints]
workspace = true
