# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Manuel Baesler and contributors

[package]
name = "audhsos-sync"
description = "The Global<T> cell that holds the global state of the kernel and of the userland runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]

[lints]
workspace = true
