# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Manuel Baesler and contributors

[package]
name = "ssh_packet"
description = "Fuzz target: ssh_packet"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "ssh_packet"
path = "src/main.rs"
test = false
bench = false
doc = false

[dependencies]
audhsos-ssh.workspace = true
crypto-rng.workspace = true
fuzz-support.workspace = true

[lints]
workspace = true
