// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Manuel Baesler and contributors

//! Unit tests, kept out of the product sources so that coverage measures
//! product code only.

mod limbs;
mod modulus;
mod reference;

use test_support::generators::Generator;
use test_support::property::{Config, check_with};

/// The four widths the arithmetic is checked at, in bits.
pub(crate) const WIDTHS: [usize; 4] = [1024, 2048, 3072, 4096];

/// Runs a property over a stated number of cases.
///
/// The reference reduces one bit at a time, so a case at four thousand
/// and ninety-six bits costs about a thousand times what a case of
/// `fe25519` costs. The count is therefore chosen per width rather than
/// left at the default of five hundred and twelve.
pub(crate) fn check_cases<G, P>(cases: u32, name: &str, generator: &G, property: P)
where
    G: Generator,
    P: Fn(&G::Value) -> Result<(), String>,
{
    let config = Config {
        cases,
        ..Config::default()
    };
    if let Err(failure) = check_with(&config, name, generator, property) {
        panic!("{failure}");
    }
}

/// The bytes of a hexadecimal string, for the vectors that are written
/// that way in the documents they come from.
pub(crate) fn unhex(text: &str) -> Vec<u8> {
    let digits: Vec<u32> = text.chars().filter_map(|c| c.to_digit(16)).collect();
    let (pairs, _) = digits.as_chunks::<2>();
    pairs
        .iter()
        .map(|[high, low]| u8::try_from(high.wrapping_mul(16).wrapping_add(*low)).unwrap_or(0))
        .collect()
}

/// Renders bytes as lower-case hexadecimal, so that a failing vector
/// prints the two values side by side.
pub(crate) fn hex(bytes: &[u8]) -> String {
    use std::fmt::Write;

    let mut rendered = String::with_capacity(bytes.len().saturating_mul(2));
    for byte in bytes {
        let _ = write!(rendered, "{byte:02x}");
    }
    rendered
}

/// A modulus of `bits` bits built from generated bytes: the top bit set
/// so that the width is the one asked for, and the low bit set so that
/// the value is odd.
pub(crate) fn modulus_bytes(bits: usize, source: &[u8]) -> Vec<u8> {
    let mut bytes = vec![0u8; bits / 8];
    for (slot, byte) in bytes.iter_mut().zip(source) {
        *slot = *byte;
    }
    if let Some(first) = bytes.first_mut() {
        *first |= 0x80;
    }
    if let Some(last) = bytes.last_mut() {
        *last |= 0x01;
    }
    bytes
}
