# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Manuel Baesler and contributors

[package]
name = "rsa"
description = "Fuzz target: rsa"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "rsa"
path = "src/main.rs"
test = false
bench = false
doc = false

[dependencies]
crypto-rsa.workspace = true
fuzz-support.workspace = true

[lints]
workspace = true
